name: tic_tac_toe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-130.0.dev <3.0.0'

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.2.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
